---
- name: A simple patching playbook
  hosts: all
  become: true
  gather_facts: true
  vars:
    datetimestamp: "{{ '%Y-%m-%d-%H-%M-%S' | strftime(ansible_date_time.epoch) }}"
    patch_log: "/var/tmp/patching-{{ datetimestamp }}.log"

  tasks:
  - name: Install patches
    dnf:
      name: '*'
      state: latest
    register:
      test_change
        
  - name: Print output if any
    ansible.builtin.debug:
      var: test_change

  - name: Executing report
    when: test_change is changed
    block:
    - name: Generate patch report
      ansible.builtin.template:
        src: "templates/PatchReport.j2"
        dest: "{{ patch_log }}"

    - name: Take a Pause
      ansible.builtin.pause:
        seconds: 5

    - name: Reboot server if changed
      ansible.builtin.reboot:
        msg: "Rebooting after patching"
        connect_timeout: 5
        reboot_timeout: 600
        test_command: whoami
