---
- name: Configure Ubuntu Server for Kubernetes v1.33
  hosts: all
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Kubernetes apt repository GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /'
        filename: kubernetes
        state: present

    - name: Add keyring for CRI-o
      ansible.builtin.apt_key:
        url: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.32/deb/Release.key
        keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg
        state: present

    - name: Add CRI-o apt repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.32/deb/ /'
        filename: cri-o
        state: present

    - name: Install Kubernetes components
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Install CRI-o package
      ansible.builtin.apt:
        name: cri-o
        state: present

    - name: Disable swap (required for Kubernetes)
      ansible.builtin.command: swapoff -a

    - name: Ensure swap is disabled in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s]+\s+swap\s+[^#\s]+)'
        replace: '# \1'

    - name: Enable and load br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Ensure br_netfilter is loaded on boot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: br_netfilter
        create: yes

    - name: Set required sysctl parameters for Kubernetes
      ansible.builtin.blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl parameters
      ansible.builtin.command: sysctl --system